version: "3.8"

networks: 
  localdev:
    driver: bridge
  controleSocial:
    external: true

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: App.Dockerfile
    ports:
      - "8999:8999"
    depends_on:
      - db
    networks:
      - controleSocial
    #healthcheck:
    #  test: curl --silent --fail http://localhost:8999/health || exit 1
    #  interval: 10s
    #  retries: 3

  db:
    container_name: db
    build:
      context: .
      dockerfile: Sql.Dockerfile
    ports:
      - "1433:1433"
    networks:
      - controleSocial
    #healthcheck:
    #  test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PControleSocial@", "-Q", "select 1"]
    #  interval: 10s
    #  retries: 3