// <auto-generated />
using System;
using ControleSocial.Domain.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleSocial.Domain.Migrations.ControleSocial
{
	[DbContext(typeof(ControleSocialContext))]
	[Migration("20200610205438_Initial")]
	partial class Initial
	{
		protected override void BuildTargetModel(ModelBuilder modelBuilder)
		{
#pragma warning disable 612, 618
			modelBuilder
					.HasAnnotation("ProductVersion", "3.1.4")
					.HasAnnotation("Relational:MaxIdentifierLength", 128)
					.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

			modelBuilder.Entity("ControleSocial.Domain.Models.ControleSocial.Usuario", b =>
					{
						b.Property<long>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("bigint")
											.HasAnnotation("SqlServer:IdentityIncrement", 1)
											.HasAnnotation("SqlServer:IdentitySeed", 1)
											.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

						b.Property<DateTime>("DataCriacao")
											.ValueGeneratedOnAdd()
											.HasColumnType("datetime2")
											.HasDefaultValueSql("getdate()");

						b.Property<string>("Email")
											.HasColumnType("nvarchar(60)")
											.HasMaxLength(60)
											.IsUnicode(true);

						b.Property<string>("Nome")
											.HasColumnType("nvarchar(80)")
											.HasMaxLength(80)
											.IsUnicode(true);

						b.Property<string>("Roles")
											.HasColumnType("nvarchar(4000)")
											.HasMaxLength(4000)
											.IsUnicode(true);

						b.Property<string>("Senha")
											.HasColumnType("nvarchar(50)")
											.HasMaxLength(50)
											.IsUnicode(true);

						b.HasKey("Id");

						b.ToTable("Usuario");

						b.HasData(
											new
									{
										Id = 1L,
										DataCriacao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
										Email = "a",
										Nome = "Fábio Henriques",
										Roles = "Admin",
										Senha = "a"
									});
					});

			modelBuilder.Entity("ControleSocial.Domain.Models.ControleSocial.UsuarioRefreshToken", b =>
					{
						b.Property<long>("Id")
											.ValueGeneratedOnAdd()
											.HasColumnType("bigint")
											.HasAnnotation("SqlServer:IdentityIncrement", 1)
											.HasAnnotation("SqlServer:IdentitySeed", 1)
											.HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

						b.Property<DateTime>("DataCriacao")
											.ValueGeneratedOnAdd()
											.HasColumnType("datetime2")
											.HasDefaultValueSql("getdate()");

						b.Property<DateTime>("DataExpiracao")
											.HasColumnType("datetime2");

						b.Property<long>("IdUsuario")
											.HasColumnType("bigint");

						b.Property<bool>("Invalido")
											.HasColumnType("bit");

						b.Property<string>("JwtId")
											.HasColumnType("nvarchar(256)")
											.HasMaxLength(256)
											.IsUnicode(true);

						b.Property<string>("Token")
											.HasColumnType("nvarchar(256)")
											.HasMaxLength(256)
											.IsUnicode(true);

						b.Property<bool>("Usado")
											.HasColumnType("bit");

						b.HasKey("Id");

						b.HasIndex("IdUsuario");

						b.ToTable("UsuarioRefreshToken");
					});

			modelBuilder.Entity("ControleSocial.Domain.Models.ControleSocial.UsuarioRefreshToken", b =>
					{
						b.HasOne("ControleSocial.Domain.Models.ControleSocial.Usuario", "Usuario")
											.WithMany("RefreshTokens")
											.HasForeignKey("IdUsuario")
											.OnDelete(DeleteBehavior.NoAction)
											.IsRequired();
					});
#pragma warning restore 612, 618
		}
	}
}
